### ISSUE TITLE
KiBuzzard Plugin Not showing in KiCad Tools after Installation

### ISSUE THREAD

**Issue by dhairyashah1** [gregdavill/KiBuzzard#50] opened 2021-06-10 12:23 UTC
1. cloned the repo in ~/.kicad/scripting/plugins
2. After multiple attempts still the plugin is not showing in KiCAD tools even after refreshing.
3. What could be a possible fix? I'm using Ubuntu 20.04 LTS.
4. Also got this error as well
![Screenshot from 2021-06-10 17-35-29](https://user-images.githubusercontent.com/64425805/121524120-99988b80-ca14-11eb-9ee9-16bee209d352.png)

**Comment by gregdavill** [comment] 2021-06-10 13:23
Is there a `KiBuzzard.log` or `error.log` file created?

**Comment by dhairyashah1** [comment] 2021-06-10 13:31
@gregdavill  yes there is a kibuzzard.log file at this path ~/.kicad/scripting/plugins/KiBuzzard. But it seems to be empty.

**Comment by gregdavill** [comment] 2021-06-10 23:17
Which version of KiCad do you have installed?

Can you see anything in the `Action Plugin` tab in the KiCad preferences? There should be an icon that appears, but on this page there is an option to not show the icon.
![Screenshot from 2021-06-11 08-42-31](https://user-images.githubusercontent.com/344310/121608696-a4ddcc80-ca91-11eb-9378-074d6eb18a46.png)

**Comment by gregdavill** [comment] 2021-06-10 23:18
I've also just noticed that I've got mine installed in `~/.kicad/scripting/`. Both should work, but maybe try that too?

**Comment by dhairyashah1** [comment] 2021-06-11 18:26
> Which version of KiCad do you have installed?
> 
> Can you see anything in the `Action Plugin` tab in the KiCad preferences? There should be an icon that appears, but on this page there is an option to not show the icon.
> ![Screenshot from 2021-06-11 08-42-31](https://user-images.githubusercontent.com/344310/121608696-a4ddcc80-ca91-11eb-9378-074d6eb18a46.png)

Nope Not getting this. Kicad version 5.1.5. Tried in scripting dir too , but same result.

**Comment by x70b1** [comment] 2021-09-25 22:45
I can see the same issue. After a clean install the plugin is not loading.

Sometimes I have this in my error.log. It means permission denied. 
```
PermissionError(13, 'Keine Berechtigung')
```

`chmod 777 -R /usr/share/kicad/scripting/plugins/KiBuzzard/` is evil, but lets the plugin load at a kicad startup. 
So we need to fix the permission for a small set of files I guess.

**Comment by gregdavill** [comment] 2021-09-26 00:34
You shouldn't see any permission issues if you're installing it into `~/.kicad/Scripting/`, since that's in your home directory.

The only thing we are trying to write to that file is the error logs, and a config file which stores all the current GUI values. Even if we're not able to write it shouldn't cause the plugin to crash and not load, so this is a bug.

**Comment by x70b1** [comment] 2021-09-26 10:11
I install it to `/usr/share/kicad/scripting/plugins/` as it works for every user on the system. Especially in the case of a prepackaged installation this is the way to go.

[InteractiveHtmlBom](https://github.com/openscopeproject/InteractiveHtmlBom) is also there and just works fine. So it would be cool if we can find out what we need to change to run it from there.

But yeah, @dhairyashah1 installed it also in his home dir and it is not loading. So i am not sure if thats the same root cause.

**Comment by gregdavill** [comment] 2021-12-31 05:02
Permission errors should be fixed with: 8c11d36b3bdee416121ac418a5248658b47ee843

**Closed by gregdavill** 2021-12-31 05:02 UTC

**Comment by x70b1** [comment] 2021-12-31 13:43
Seems to work. Awesome! :sunglasses:
